# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Nicolas Jorge
title: Economist
email: ""
website: https://nicolasjorge82.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: NicolsJorge2
github_username:  nicolasjorge82
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: ariel-nicolás-jorge-25629718
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "G-KZK622TCWN"
google_analytics: "G-KZK622TCWN"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Nicolás, economist oriented to quantitative analysis and problem solving. I'm attracted to problems where solid quantitative answers are required but data is scarce or incomplete.
content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: INAI
        link: http://inai.org.ar
        # link_text: boringcompany.com
        sub_title: Economist
        caption: 2011 - Present
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          Impact analisis on public policy and trade agreements. Medium and long term projections for agriculture. Computational economic modelling.

      - layout: left
        title: IADB Project
        link: https://www.argentina.gob.ar/agricultura
        # link_text: boringcompany.com
        sub_title: Consultant
        caption: 2009-2011
        quote: >
         
        description: | # this will include new lines to allow paragraphs
          Policy analysis. Agricultural projections. Computational model maintainance and extension.

      - layout: left
        title: Ministry of Agriculture, Livestock, Fisheries and Forestry
        link: https://www.argentina.gob.ar/agricultura
        # link_text: boringcompany.com
        sub_title: Economist
        caption: 2006-2009
        quote: >
         
        description: | # this will include new lines to allow paragraphs
          Impact analisis on trade negotiations. Computational economic modelling.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: UTDT (Torcuato Di Tella University)
        caption: 2006 - 2008
        sub_title: Postgraduate Certificate in Economics
        quote: >
         
        description: | # this will include new lines to allow paragraphs
          Main subjects: Statistical Inference, Econometrics, Time Series, Macroeconometrics, Numerical Methods, Dynamic Programming, Game Theory, Microeconomics, Macroeconomics

      - layout: left
        title: UBA (University of Buenos Aires)
        caption: 2000 - 2004
        sub_title: Licentiate in Economics
        quote: >
          
        description: | # this will include new lines to allow paragraphs        
          Main subjects: Econometrics, Microeconomics, Macroeconomics, Economic Growth, Money, Credit and Banks, Capital Markets

  - title: Other skills
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Quantitative modelling (GAMS)
      - Data analysis (PANDAS, R)
      - OOP (PYTHON, Visual Basic .NET)



# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
